name: TODO
description: A Todo List App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  intl: ^0.17.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.1
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: google_fonts/Poppins-Regular.ttf
        - asset: google_fonts/Poppins-Black.ttf
        - asset: google_fonts/Poppins-BlackItalic.ttf
        - asset: google_fonts/Poppins-Bold.ttf
        - asset: google_fonts/Poppins-BoldItalic.ttf
        - asset: google_fonts/Poppins-ExtraBold.ttf
        - asset: google_fonts/Poppins-ExtraBoldItalic.ttf
        - asset: google_fonts/Poppins-ExtraLight.ttf
        - asset: google_fonts/Poppins-ExtraLightItalic.ttf
        - asset: google_fonts/Poppins-Italic.ttf
        - asset: google_fonts/Poppins-Light.ttf
        - asset: google_fonts/Poppins-LightItalic.ttf
        - asset: google_fonts/Poppins-Medium.ttf
        - asset: google_fonts/Poppins-MediumItalic.ttf
        - asset: google_fonts/Poppins-Regular.ttf
        - asset: google_fonts/Poppins-SemiBold.ttf
        - asset: google_fonts/Poppins-SemiBoldItalic.ttf
        - asset: google_fonts/Poppins-Thin.ttf
        - asset: google_fonts/Poppins-ThinItalic.ttf
  assets:
    - assets/
    - google_fonts/
